### ISSUE TITLE
Node INFO Table not correct 

### ISSUE THREAD

**Issue by sasidharvarada** [likhithkanigolla/zf-dt-frontend#27]
For the node WM-WD-KH96-00

**Comment by likhithkanigolla** [comment]
Can't Reproduce the issue.

**Comment by likhithkanigolla** [comment]
<img width="693" alt="image" src="https://github.com/user-attachments/assets/b55df011-71af-4339-b91f-9410bb931f65">
Please check it again by clearing cache/in incognito window. If you still face issue feel free to reopen the issue

**Comment by sasidharvarada** [comment]
Now its showing correctly
